##
# CAS Cloud Bus Configuration
#
spring:
  cloud:
    bus:
      enabled: false
  ##
  # CAS AspectJ 配置
  #
  aop:
    proxy-target-class: true
    auto: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  ##
  # CAS Thymeleaf View 配置
  #
  thymeleaf:
    mode: HTML
    cache: true
    encoding: UTF-8
##
# CAS Server Context 配置
#
server:
  connection-timeout: 20000
  context-path: /cas
  tomcat:
    basedir: build/tomcat
    remote-ip-header: X-FORWARDED-FOR
    uri-encoding: UTF-8
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    port-header: X-Forwarded-Port
    max-threads: 10
    max-http-post-size: 2097152
    accesslog:
      pattern: '%t %a \%r\ %s (%D ms)'
      suffix: .log
      enabled: true
  port: 8443
  max-http-header-size: 2097152
  ##
  # CAS Web Application Session 配置
  #
  session:
    tracking-modes: COOKIE
    cookie:
      http-only: true
    timeout: 300
  context-parameters:
    isLog4jAutoInitializationDisabled: true
  compression:
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    include-stacktrace: ALWAYS
  ##
  # 证书配置 如果不用https,enabled为false
  #
  ssl:
    enabled: false
#    key-password: changeit
#    key-store: file:/etc/cas/thekeystore
#    key-store-password: changeit
  use-forward-headers: true
security:
  basic:
    path: /cas/status/**
    authorize-mode: role
    enabled: false
endpoints:
  restart:
    enabled: false
  sensitive: true
  shutdown:
    enabled: false
  enabled: false
##
# CAS 身份验证凭证
#
#cas:
#  authn:

    # 写死的静态用户
    #    accept:
    #      users: admin::aaa
#    jdbc:
#      query[0]:
#        healthQuery: select 1
#        dialect: org.hibernate.dialect.MySQLDialect
#        driverClass: com.mysql.jdbc.Driver
#        #        fieldDisabled: disabled # 对应数据库字段,1为禁用
#        fieldExpired: status # 对应数据库字段,1为过期
#        fieldPassword: password # 对应数据库字段,密码
#        sql: select * from tbl_user where username=?
#        url: jdbc:mysql://172.30.220.233/zzzgd?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#        user: root
#        password: zhangguodong1
#        # 密码加密算法
#        passwordEncoder:
#          type: NONE # NONE|DEFAULT|STANDARD|BCRYPT|SCRYPT|PBKDF2|com.example.CustomPasswordEncoder
#          characterEncoding: UTF-8
##        encodingAlgorithm: # 算法
#        # 加盐


  tgc:
    secure: false
  serviceRegistry:
    initFromJson: true
management:
  security:
    sessions: if_required
    roles: ACTUATOR,ADMIN
    enabled: true
  context-path: /status
  add-application-context-header: false